/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TheiaGraph {
  meta: {
    generated_at: string;
    source_count: number;
    projection: "pca" | "umap" | "tool-vector";
    feature_dim?: number;
  };
  nodes: {
    id: string;
    title: string;
    preview?: string | null;
    started_at: string;
    duration_sec: number;
    tool_count: number;
    message_count?: number;
    model?: string;
    summary?: string | null;
    initial_prompt?: string | null;
    position: {
      x: number;
      y: number;
    };
    features?: null | number[];
    parent_id?: string | null;
  }[];
  edges: {
    source: string;
    target: string;
    kind: "memory-share" | "cross-search" | "tool-overlap" | "subagent";
    weight: number;
    evidence?: Record<string, unknown>;
  }[];
}
